
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjddnsmkymfvriwstiiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqZGRuc21reW1mdnJpd3N0aWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMzkxODgsImV4cCI6MjA1ODcxNTE4OH0.Ss2rbRoZY7-8mjIYHGNWB1DHxKJ-FkxkAm2mA8-fIWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
